name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploy to Vercel
        run: |
          npx vercel --prod -t ${{ secrets.VERCEL_TOKEN }} \
          -m githubCommitSha=${{ github.sha }} \
          -m githubCommitAuthorName=${{ github.actor }} \
          -m githubCommitMessage="${{ github.event.head_commit.message }}" \
          -m githubCommitRef=${{ github.ref }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
